name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GH_MANAGE_PKG}}
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"
      - name: build-push
        uses: docker/build-push-action@v5
        env:
          ARTIFACT: donc-counter
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/jboureux/${{env.ARTIFACT}}:${{ steps.date.outputs.date }}, ghcr.io/jboureux/${{env.ARTIFACT}}:latest
  

      
